### ISSUE TITLE
Use proper domain for packaging

### ISSUE THREAD

**Issue by Kryszak** [Kryszak/gwatlin#24]
We should pick and change package domain to not use `com`, since it's meant to be used for commercial projects.

My other projects use `net` domain, other valid could be `org` or `io`. 

I think most common domain for OSS projects is `org`, like all Apache libraries.

**Comment by fanonwue** [comment]
Do you plan to just rename the maven package or do you want to stay consistent and also rename all packages?

**Comment by Kryszak** [comment]
The plan is to rename maven package's group and packages inside of the app

**Comment by fanonwue** [comment]
That's probably the better way, true.

As for the domain, I think all 3 options are fine. `org` is something for bigger projects with larger organizations in my books.

So it just comes down to
1. `net.kryszak.gwatlin`
2. `io.kryszak.gwatlin`

for me.

Since your other projects already use 1, I'd just go with that.

**Comment by Kryszak** [comment]
Let's go with `net` then.

**Comment by Kryszak** [comment]
Update: default namespace created on Maven Central when logging in with Github is: `io.github.kryszak`
I propose going with this one to make planned Maven Central upload faster (https://github.com/Kryszak/gwatlin/issues/42)
